baseURL = "https://masaqu.id"
canonifyurls = true
title = "masaqu.id"
author = "masaquid"
languageCode = "ja-jp"
hasCJKLanguage = true
theme = "robust"
disqusShortname = "masaquid"
copyright = """
&copy; masaqu.id
<a rel='license' href='http://creativecommons.org/licenses/by-sa/4.0/'>
  <img alt='クリエイティブ・コモンズ・ライセンス' src='https://i.creativecommons.org/l/by-sa/4.0/80x15.png' />
</a>
"""

[params]
  # description = "This is site description"
  dateformat = "2006/01/02"
  # Fonts settings.
  googlefonts = "https://fonts.googleapis.com/css?family=Lato|Noto+Sans+JP&display=swap" # Optional, Include google fonts.
  fontfamily = "Lato, 'Noto Sans JP', 'Hiragino Kaku Gothic Pro', Meiryo, sans-serif" # Optional, Override body font family.
  # logofontfamily = "Lobster, cursive" # Optional, Override logo font.

[params.author]
  thumbnail = "/images/avatar.png"
  name = "@masaquid"
  description = """
  <p>
    元 地方で働くPHPプログラマー<br>
    現在はオリジナル商品の企画・開発や販促品の制作会社に勤めています
  </p>
  <a href="/pages/about/">このブログについてと、プロフィールはこちら</a>
  """

  twitter  = "https://twitter.com/masaquid"
  # facebook = "https://www.facebook.com/masaquid"
  github   = "https://github.com/masaquid"
  eight    = "https://www.facebook.com/masaquid"
  mail     = "mailto:masaquid@gmail.com"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"